# Dependencies
markdown:         kramdown
highlighter:      rouge

# Permalinks
permalink:         pretty

# Setup
title:            Earthsea
tagline:          'A fansite'
description:      'A fansite for the Earthsea saga, written by <a href="http://www.ursulakleguin.com/" target="_blank">Ursula k. Leguin</a>.'
url:                 https://premachu.github.io
paginate:            2 # number of posts per page
baseurl:             /hyde/

author:
  name:           'Premachu'
  url:            https://premachu.github.io


# Disqus comments:
disqus:           true
shortname:        premachu.disqus.com

# Custom vars
version:          3.0

github:
  repo:           https://github.com/Premachu/hyde

# This is the list of pages to incldue in the header of the website.
pages_list:       {'About':'/about','Archive':'/archive','Feed':'/atom.xml'}
