# Dependencies
markdown:         kramdown
highlighter:      rouge

# Permalinks
permalink:         pretty

# Setup
title:            Hyde
tagline:          'A Jekyll theme'
description:      'A brazen two-column <a href="http://jekyllrb.com" target="_blank">Jekyll</a> theme that pairs a prominent sidebar with uncomplicated content. Made by <a href="https://twitter.com/mdo" target="_blank">@mdo</a>.'
url:                 "https://premachu.github.io"
paginate:            5
baseurl:             "/hyde/"

author:
  name:           'Mark Otto'
  url:            https://twitter.com/mdo

# Custom vars
version:          3.0

github:
  repo:           https://github.com/Premachu/hyde
