# Dependencies
markdown:         kramdown
highlighter:      rouge

# Permalinks
permalink:         pretty

# Setup
title:            Earthsea
tagline:          'A fansite'
description:      'A fansite for the Earthsea saga, written by <a href="http://www.ursulakleguin.com/" target="_blank">Ursula k. Leguin</a>.'
url:                 https://premachu.github.io
paginate:            5
baseurl:             /hyde/

author:
  name:           'Premachu'
  url:            https://premachu.github.io

# Custom vars
version:          3.0

github:
  repo:           https://github.com/Premachu/hyde
